version: 2
jobs:
  build:
    working_directory: ~/recall
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Checkout /functions dir
          command: cd functions
      - run:
          name: Install Dependencies
          command: npm install
